server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@metaverse.ohgiraffers.com:1521/xe
    username: C##UNIVERSE
    password: UNIVERSE

jwt:
  secret: asdfjp298pafo1320efqw0udvnh0er0h412r08byfdq9dsvh02143908hfeqwn80fdqs0nfdqs0n412013rq0nqefn08dfas0das730732g86923

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package: com.dream.universe
  configuration:
    map-underscore-to-camel-case: true
